version: 2

project_name: dockwarden

builds:
  - id: dockwarden
    main: ./cmd/dockwarden
    binary: dockwarden
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/emon5122/dockwarden/internal/meta.Version={{.Version}}
      - -X github.com/emon5122/dockwarden/internal/meta.Commit={{.Commit}}
      - -X github.com/emon5122/dockwarden/internal/meta.BuildDate={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    files:
      - README.md
      - LICENSE
      - DESIGN.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: emon5122
    name: dockwarden
  draft: false
  prerelease: auto
  name_template: "DockWarden {{ .Version }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
